version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  - package-ecosystem: "npm"
    directory: "/gateway"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/storefront"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gradle"
    directory: "/services"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/infra/docker"
    schedule:
      interval: "weekly"

  - package-ecosystem: "terraform"
    directory: "/infra/terraform"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
