apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: dachshaus-public
spec:
  replicas: 3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  namespace: dachshaus-services
spec:
  replicas: 3
