apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  namespace: dachshaus-services
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      serviceAccountName: auth
      containers:
        - name: auth
          image: auth:latest
          ports:
            - containerPort: 8080
