apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart
  namespace: dachshaus-services
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cart
  template:
    metadata:
      labels:
        app: cart
    spec:
      serviceAccountName: cart
      containers:
        - name: cart
          image: cart:latest
          ports:
            - containerPort: 8080
