apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: auth-service
  namespace: dachshaus-kafka
  labels:
    strimzi.io/cluster: dachshaus-cluster
spec:
  authentication:
    type: scram-sha-512
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: user-registered
        operations: [Write, Describe]
