apiVersion: apps/v1
kind: Deployment
metadata:
  name: storefront
  namespace: dachshaus-public
spec:
  replicas: 2
  selector:
    matchLabels:
      app: storefront
  template:
    metadata:
      labels:
        app: storefront
    spec:
      containers:
        - name: storefront
          image: storefront:latest
          ports:
            - containerPort: 3000
