apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: gateway-to-services
  namespace: dachshaus-services
spec:
  podSelector: {}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              name: dachshaus-public
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: services-to-data
  namespace: dachshaus-data
spec:
  podSelector: {}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              name: dachshaus-services
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-all-default
  namespace: dachshaus-services
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
