apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gateway-secrets
  namespace: dachshaus-public
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcpsm-secret-store
    kind: SecretStore
  target:
    name: gateway-secrets
  data:
    - secretKey: HMAC_SECRET
      remoteRef:
        key: gateway-hmac-secret
